// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20190504175911_FacebookDataPage")]
    partial class FacebookDataPage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Common.Entities.FacebookPage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("MaxAddMembersPerWeek");

                    b.Property<string>("NamePage");

                    b.Property<string>("UrlPage");

                    b.HasKey("Id");

                    b.ToTable("FacebookPages");
                });

            modelBuilder.Entity("Common.Entities.FacebookPageData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("CountMembers");

                    b.Property<DateTime?>("DateUpdate");

                    b.Property<long>("IdPage");

                    b.Property<long?>("PageId");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("FacebookPageData");
                });

            modelBuilder.Entity("Common.Entities.FacebookPageData", b =>
                {
                    b.HasOne("Common.Entities.FacebookPage", "Page")
                        .WithMany()
                        .HasForeignKey("PageId");
                });
#pragma warning restore 612, 618
        }
    }
}
